In [1]:
import sys
sys.path.append('/Users/diegofiori/Desktop/epfl/master_thesis/master_thesis/')

In [2]:
from simulation import Simulation
from input_reader import ImageReader
from diagram_derivatives import DiagramDerivative
%load_ext autoreload
%autoreload 2

In [3]:
from giotto.homology import CubicalPersistence

In [4]:
simulation = Simulation('/Users/diegofiori/Desktop/epfl/master_thesis/Reverse/results_132.h5')

In [5]:
image_reader = ImageReader()
images = image_reader.read('/Users/diegofiori/Desktop/epfl/master_thesis/Reverse/results_132.h5')

In [6]:
images.shape

(2400, 244, 324)

In [8]:
diagrams = CubicalPersistence(n_jobs=-1).fit_transform(images)

In [9]:
diagrams.shape

(2400, 715, 3)

In [10]:
import pickle as pkl
pkl.dump(diagrams, open('diagrams.pickle', 'wb'))

In [11]:
import numpy as np

In [12]:
def select_diagrams_for_fixed_angle(diagrams, angle_ind, info):
    inner_order = info['inner_sequence']
    inner_nb = [info[key] for key in inner_order]
    list_of_qs = []
    new_diagrams = []
    k = 1
    for i in range(0, len(diagrams), inner_nb[0]):
        if i >= inner_nb[0] * inner_nb[1] * k:
            list_of_qs.append(np.concatenate(new_diagrams))
            k += 1
            new_diagrams = []
           
        new_diagrams.append(np.expand_dims(diagrams[i+angle_ind], axis=0))
    list_of_qs.append(new_diagrams)
    return list_of_qs

In [13]:
diagrams_angle_0_for_qs = select_diagrams_for_fixed_angle(diagrams, 0, image_reader.structure_)

In [14]:
diagram_angle_0_density = diagrams_angle_0_for_qs[0]

In [15]:
diagram_angle_0_density

array([[[ -3.1344161 ,   1.74782515,   0.        ],
        [ -2.82930326,  -1.63381732,   0.        ],
        [ -2.25594354,  -1.78315163,   0.        ],
        ...,
        [-89.86339569, -89.86339569,   1.        ],
        [-89.86339569, -89.86339569,   1.        ],
        [-89.86339569, -89.86339569,   1.        ]],

       [[ -3.10172772,   1.74749136,   0.        ],
        [ -2.81804609,  -1.66579366,   0.        ],
        [ -2.25497651,  -1.78459132,   0.        ],
        ...,
        [-89.86339569, -89.86339569,   1.        ],
        [-89.86339569, -89.86339569,   1.        ],
        [-89.86339569, -89.86339569,   1.        ]],

       [[ -3.08099341,   1.74722672,   0.        ],
        [ -2.82171583,  -1.68491161,   0.        ],
        [ -2.25427723,  -1.7808181 ,   0.        ],
        ...,
        [-89.86339569, -89.86339569,   1.        ],
        [-89.86339569, -89.86339569,   1.        ],
        [-89.86339569, -89.86339569,   1.        ]],

       [[ -3.068227

In [16]:
len(diagram_angle_0_density) # nb of time steps 

5

In [19]:
diagram_derivative = DiagramDerivative(metric='heat', n_jobs=-1).fit_transform(diagram_angle_0_density)

{'metric': 'heat', 'metric_params': None, 'n_jobs': -1, 'order': 2.0}


ValueError: all input arrays must have the same shape

In [98]:
diagram_derivative

array([0.45939712, 0.67970666, 0.62160047, 0.50318071])

In [39]:
def select_diagrams_for_fixed_time(diagrams, time_ind, info):
    inner_order = info['inner_sequence']
    inner_nb = [info[key] for key in inner_order]
    list_of_qs = []
    for i in range(0, len(diagrams), inner_nb[0]*inner_nb[1]):
        new_diagrams = diagrams[i + inner_nb[1]*time_ind: i + inner_nb[1]*time_ind + inner_nb[0]]
        new_diagrams = np.concatenate([new_diagrams, np.expand_dims(diagrams[i + inner_nb[1]*time_ind], axis=0)])
        list_of_qs.append(new_diagrams)
    return list_of_qs

In [72]:
diagrams_time_0_for_qs = select_diagrams_for_fixed_time(diagrams, 0, image_reader.structure_)

In [73]:
diagrams_time_0_for_density = diagrams_time_0_for_qs[0]

In [99]:
diagram_space_derivatives = DiagramDerivative(metric='heat', n_jobs=-1).fit_transform(diagrams_time_0_for_density)

{'h': None, 'metric': 'heat', 'metric_params': None, 'n_jobs': -1, 'order': 2.0}


In [100]:
diagram_space_derivatives

array([0.52378086, 0.53785959, 0.45939704, 0.56744695, 0.55175683,
       0.42230597, 0.53785936, 0.42824045, 0.61664316, 0.4593968 ,
       0.48312162, 0.51229558, 0.53785919, 0.42824033, 0.42230578,
       0.53308358, 0.53308357, 0.53308357, 0.53308358, 0.42230578,
       0.42230579, 0.4223058 , 0.42230581, 0.42230583, 0.42230584,
       0.42230586, 0.42230588, 0.4223059 , 0.42230593, 0.42230595,
       0.42230598, 0.53785945, 0.42230604, 0.42230607, 0.4223061 ,
       0.42230614, 0.42230617, 0.42230623, 0.42824083, 0.53785987,
       0.42230638, 0.42824099, 0.53786006, 0.42230653, 0.42230657,
       0.42230661, 0.42230665, 0.42230668, 0.42230672, 0.42230674,
       0.42230677, 0.4827204 , 0.60231291, 0.42230682, 0.42230683,
       0.43564352, 0.42230683, 0.42230683, 0.42230683, 0.42230683,
       0.42230682, 0.4223068 , 0.43564347, 0.62916908, 0.43476083,
       0.53308478, 0.43476077, 0.45405608, 0.42230662, 0.42230659,
       0.42230656, 0.42230652, 0.42230648, 0.42230645, 0.53785

In [84]:
from giotto.diagrams import Amplitude

In [90]:
Amplitude(n_jobs=-1).fit_transform(diagram_angle_0_density)

array([[3.54380003],
       [3.52979025],
       [3.5273665 ],
       [3.5323529 ],
       [3.53340377]])

In [89]:
Amplitude(n_jobs=-1).fit_transform(diagrams_time_0_for_density)

array([[4.31539328],
       [4.31616499],
       [4.31699677],
       [4.31776437],
       [4.3184162 ],
       [3.54609193],
       [2.54660247],
       [2.54327846],
       [2.53975183],
       [2.53606174],
       [2.53225894],
       [4.31923818],
       [4.31980377],
       [4.32050153],
       [4.32141204],
       [4.32257051],
       [2.52840934],
       [2.52459803],
       [2.52092897],
       [2.5175225 ],
       [2.51450953],
       [4.32395319],
       [4.32547452],
       [4.32699891],
       [4.32836466],
       [4.32941747],
       [2.51202251],
       [2.51018405],
       [2.50909596],
       [2.50882878],
       [2.50941408],
       [4.33004799],
       [4.33022024],
       [4.32997875],
       [4.32943682],
       [4.3287432 ],
       [2.51084197],
       [2.51306157],
       [2.51598645],
       [2.51950478],
       [2.52348868],
       [4.32801416],
       [4.32735372],
       [4.32682853],
       [4.32646971],
       [4.32627892],
       [2.52778654],
       [2.532